# Generated by Django 3.0.5 on 2020-04-30 11:12

import ColDocDjango.ColDocApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ColDocApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', ColDocDjango.ColDocApp.models.UUID_Field(db_index=True)),
                ('environ', models.CharField(db_index=True, max_length=100)),
                ('optarg', models.CharField(blank=True, max_length=300)),
                ('extension', models.TextField(blank=True, default='', help_text='newline-separated list of extensions', max_length=100)),
                ('lang', models.TextField(blank=True, default='', help_text='newline-separated list of languages', max_length=100)),
                ('original_filename', models.CharField(blank=True, help_text='the filename whose content was copied in this blob (and children of this blob)', max_length=1000)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation')),
                ('blob_modification_time', models.DateTimeField(default=None, null=True, verbose_name='time of last modification of content')),
                ('latex_time', models.DateTimeField(default=None, null=True, verbose_name='time of last run of latex')),
                ('latex_return_codes', models.CharField(blank=True, max_length=2000)),
                ('access', models.CharField(choices=[('open', 'view and LaTeX visible to everybody'), ('public', 'view visible to everybody, LaTeX restricted'), ('private', 'visible only to editors, and authors of this blob')], default='public', max_length=15, verbose_name='access')),
                ('latex_documentclass_choice', models.CharField(choices=[('auto', 'use `main` class for sections and whole document, `standalone` class for others'), ('main', 'use the class of the main document (usually associated to UUID 001)'), ('standalone', 'use `standalone` documentclass'), ('article', 'use `article` documentclass'), ('book', 'use `book` documentclass')], default='auto', max_length=15, verbose_name='documentclass used to compile')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('coldoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColDocApp.DColDoc')),
            ],
            options={
                'verbose_name': 'Metadata',
                'permissions': [('view_view', 'can view_view anywhere'), ('view_blob', 'can view_blob anywhere'), ('change_blob', 'can change_blob anywhere'), ('download', 'can download anywhere'), ('commit', 'can commit anywhere')],
            },
        ),
        migrations.CreateModel(
            name='UUID_Tree_Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', ColDocDjango.ColDocApp.models.UUID_Field(db_index=True)),
                ('child', ColDocDjango.ColDocApp.models.UUID_Field(db_index=True)),
                ('coldoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColDocApp.DColDoc')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('value', models.CharField(blank=True, db_index=True, max_length=120)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UUID.DMetadata')),
            ],
        ),
    ]
