# Generated by Django 3.1.1 on 2020-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UUID', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmetadata',
            name='environ',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
