# Generated by Django 3.1.1 on 2020-10-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UUID', '0002_environ_can_be_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmetadata',
            options={'permissions': [('view_view', 'can view_view anywhere'), ('view_log', 'can view_log anywhere'), ('view_blob', 'can view_blob anywhere'), ('change_blob', 'can change_blob anywhere'), ('download', 'can download anywhere'), ('commit', 'can commit anywhere')], 'verbose_name': 'Metadata'},
        ),
    ]
