# Generated by Django 3.1.1 on 2020-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UUID', '0005_20201009_update_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmetadata',
            name='latex_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='time of last run of latex'),
        ),
    ]
