# Generated by Django 4.1.2 on 2023-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UUID', '0009_extrametadata_second_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmetadata',
            name='order_in_document',
            field=models.PositiveIntegerField(default=2147483647, verbose_name='enumerates blobs in the order in which they appear in the document'),
        ),
    ]
