# Generated by Django 4.1.2 on 2023-10-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UUID', '0010_dmetadata_order_in_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=4)),
                ('text', models.TextField(max_length=1000)),
                ('line', models.IntegerField(default=0)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UUID.dmetadata')),
            ],
            options={
                'ordering': ['blob__order_in_document', 'lang', 'text'],
            },
        ),
    ]
