#!/usr/bin/env python3

"""See ColDocDjango/latex.py
"""

import os, sys, shutil, subprocess, argparse, json, glob

from os.path import join as osjoin

if __name__ == '__main__':
    for j in ('','.'):
        if j in sys.path:
            sys.stderr.write('Warning: deleting %r from sys.path\n',j)
            del sys.path[sys.path.index(j)]
    #
    a = os.path.realpath(sys.argv[0])
    a = os.path.dirname(a)
    a = os.path.dirname(a)
    assert os.path.isdir(a), a
    if a not in sys.path:
        sys.path.insert(0, a)
    del a
    #
    from ColDoc import loggin

import logging
logger = logging.getLogger(__name__)

import ColDoc.latex

cmd_help = ColDoc.latex.cmd_help + """

    dedup_html
       dedup some parts of HTML generated by PlasTeX, and put a single copy in /static
"""

def main(argv):
    # parse arguments
    COLDOC_SITE_ROOT = os.environ.get('COLDOC_SITE_ROOT')
    parser = ColDoc.latex.prepare_parser(cmd_help=cmd_help)
    parser.add_argument('--coldoc-nick',type=str,\
                        help='nickname for the coldoc document',
                        required=True)
    parser.add_argument('--coldoc-site-root',type=str,\
                        help='root of the coldoc portal', default=COLDOC_SITE_ROOT,
                        required=(COLDOC_SITE_ROOT is None))
    parser.add_argument('--url-UUID',type=str,\
                        help='URL of the website that will show the UUIDs, used by my \\uuid macro in PDF')
    args = parser.parse_args(argv[1:])
    #
    COLDOC_SITE_ROOT = args.coldoc_site_root
    os.environ['COLDOC_SITE_ROOT'] = args.coldoc_site_root
    assert os.path.isdir(COLDOC_SITE_ROOT), COLDOC_SITE_ROOT
    #
    args.blobs_dir = blobs_dir = osjoin(COLDOC_SITE_ROOT,'coldocs',args.coldoc_nick,'blobs')
    assert os.path.isdir(args.blobs_dir) , args.blobs_dir
    #
    args.coldoc_dir = coldoc_dir = osjoin(COLDOC_SITE_ROOT,'coldocs',args.coldoc_nick)
    #
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ColDocDjango.settings')
    import django
    django.setup()
    from django.conf import settings as django_settings
    #
    import ColDocDjango.ColDocApp.models as coldocapp_models
    import ColDocDjango.UUID.models as  blob_models
    from ColDocDjango.transform import squash_helper_ref
    from ColDoc.latex import prepare_options_for_latex
    #
    matches = list(coldocapp_models.DColDoc.objects.filter(nickname = args.coldoc_nick))
    if len(matches) > 1 :
        raise ValueError("Too many ColDoc with nick %r." % (args.coldoc_nick,) )
    coldoc = matches[0]
    #
    # read options
    options = prepare_options_for_latex(coldoc_dir, blobs_dir, blob_models.DMetadata, coldoc)
    options['coldoc'] = coldoc
    options['url_UUID'] = args.url_UUID
    options['coldoc_site_root']  = args.coldoc_site_root
    options['dedup_root'] = django_settings.DEDUP_ROOT
    options['dedup_url'] = django_settings.DEDUP_URL
    #
    a = osjoin(COLDOC_SITE_ROOT,'config.ini')
    import configparser
    config = configparser.ConfigParser()
    config.read([a])
    for k in 'server_url', 'hostname':
        options[k] = config['django'][k]
    #
    import functools
    options["squash_helper"] = functools.partial(squash_helper_ref, coldoc)
    options['metadata_class'] = blob_models.DMetadata
    #
    if args.command[0] == 'dedup_html':
        known = set()
        for src in glob.glob(osjoin(blobs_dir,'UUID','*','*','*','*_html')):
            replacements = ColDoc.latex.dedup_html(src, options)
            for a,b in replacements: known.add(b)
        #
        for k in os.listdir(django_settings.DEDUP_ROOT):
            if k not in known:
                logger.warning('Subdir %r of %r is not used anymore, may delete', k, django_settings.DEDUP_ROOT)
        return True
    #
    return ColDoc.latex.main_by_args(args,options)


if __name__ == '__main__':
    ret = main(sys.argv)
    sys.exit(0 if ret else 13)
