# Generated by Django 3.1.1 on 2020-09-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldocuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
