# Generated by Django 3.1.1 on 2020-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0002_20200922_coldocuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcoldoc',
            name='latex_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='time of last run of latex'),
        ),
    ]
