# Generated by Django 3.1.1 on 2020-10-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0003_20201010_allow_empty_latex_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcoldoc',
            name='author_can_add_blob',
            field=models.BooleanField(default=True, verbose_name='An user can add a children if s/he is the author of the blob'),
        ),
    ]
