# Generated by Django 4.0 on 2022-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0006_remove_dcoldoc_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcoldoc',
            name='languages',
            field=models.TextField(blank=True, max_length=200, verbose_name='languages supported (one ISO_639-3 three letter code per line)'),
        ),
    ]
