# Generated by Django 4.0 on 2022-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0007_dcoldoc_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcoldoc',
            name='author_can_add_blob',
            field=models.BooleanField(default=True, verbose_name='An user can add a child node if s/he is the author of the blob'),
        ),
    ]
