# Generated by Django 4.1.2 on 2022-10-15 07:33

import ColDocApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0008_alter_dcoldoc_author_can_add_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', ColDocApp.models.UUID_Field(db_index=True)),
                ('lang', models.CharField(max_length=4)),
                ('text', models.TextField(max_length=1000)),
                ('coldoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColDocApp.dcoldoc')),
            ],
            options={
                'ordering': ['coldoc', 'uuid', 'lang', 'text'],
            },
        ),
    ]
