# Generated by Django 4.1.2 on 2022-11-30 10:03

import ColDocApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0009_text_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcoldoc',
            name='languages',
            field=models.TextField(blank=True, max_length=200, validators=[ColDocApp.models.validate_languages], verbose_name='languages supported (one ISO_639-3 three letter code per line)'),
        ),
    ]
