# Generated by Django 4.1.2 on 2023-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0010_alter_dcoldoc_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcoldoc',
            name='graphic_mul_template',
            field=models.TextField(blank=True, default='\n\\ifplastex\n\\includegraphics{%(filename)s}\n\\else\n\\begin{figure}\n\\begin{center}\n\\includegraphics[width=0.5\\textwidth]{%(filename_no_ext)s}\n\\caption{\n\\CDLeng Figure for \n\\CDLita Figura per \n\\CDLfra Figure par \n\\CDLspa Figura por \n\\CDLdeu Abbildung zum\n\\CDLrus Рисунок для \n\\ref{UUID:%(parent_uuid)s}}\n\\end{center}\n\\end{figure}\n\\fi\n', max_length=1000),
        ),
        migrations.AddField(
            model_name='dcoldoc',
            name='graphic_template',
            field=models.TextField(blank=True, default='\n\\ifplastex\n\\includegraphics{%(filename)s}\n\\else\n\\begin{figure}\n\\begin{center}\n\\includegraphics[width=0.5\\textwidth]{%(filename_no_ext)s}\n\\caption{Figure for \\ref{UUID:%(parent_uuid)s}}\n\\end{center}\n\\end{figure}\n\\fi\n', max_length=1000),
        ),
    ]
