# Generated by Django 4.1.2 on 2023-10-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0011_dcoldoc_graphic_mul_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text_Catalog',
        ),
    ]
