# Generated by Django 4.1.2 on 2023-10-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColDocApp', '0012_delete_text_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcoldoc',
            name='pdflatex_fortify',
            field=models.BooleanField(default=True, verbose_name='add some parameters to `pdflatex` to fortify againsta hacks; disable only if you trust your users (and you wish to use `imakeidx`)'),
        ),
    ]
